### ISSUE TITLE
Can We change the view.

### ISSUE THREAD

**Issue by MustafaAndroid** [massivedisaster/ArcToolbarView#19]
It is possible to change the view of archToolbarView like google Tez app (Home Screen) Can you add this feature in this cool library..

**Comment by extmkv** [comment]
Can you share an example? A video or a nimage would be great.On 19 Oct 2019 08:07, MustafaAndroid <notifications@github.com> wrote:It is possible to change the view of archToolbarView like google Tez app (Home Screen) Can you add this feature in this cool library..

**Comment by MustafaAndroid** [comment]
![Uploading Screenshot_2019-10-19-16-41-00-780_com.google.android.apps.nbu.paisa.user.png…]()
yep this is image of google tez bro

**Comment by MustafaAndroid** [comment]
`![Screenshot_2019-10-19-16-41-00-780_com google android apps nbu paisa user](https://user-images.githubusercontent.com/47474589/67144038-c3c19680-f28f-11e9-8eab-bac4f7c67026.png)`
Yep bro this is image of google tez...

**Comment by extmkv** [comment]
I see, unfortunately the Google Tez view have different concept.
